# Generated by Django 3.2.9 on 2021-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_open_for_bids',
            field=models.BooleanField(default=True),
        ),
    ]
